const express = require('express');
const router = express.Router();
const upload = require('../middleware/upload.middleware');
const { validateFileSignatures } = require('../middleware/security.middleware');
const ctrl = require('../controllers/convert.controller');

router.post('/jpg-to-pdf', upload.array('files', 20), validateFileSignatures, ctrl.imageToPDF);
router.post('/png-to-pdf', upload.array('files', 20), validateFileSignatures, ctrl.imageToPDF);
router.post('/image-to-pdf', upload.array('files', 20), validateFileSignatures, ctrl.imageToPDF);
router.post('/word-to-pdf', upload.single('file'), validateFileSignatures, ctrl.wordToPDF);
router.post('/word-to-text', upload.single('file'), validateFileSignatures, ctrl.wordToText);
router.post('/word-to-html', upload.single('file'), validateFileSignatures, ctrl.wordToHTML);
router.post('/text-to-word', upload.single('file'), validateFileSignatures, ctrl.textToWord);
router.post('/text-to-pdf', upload.single('file'), validateFileSignatures, ctrl.textToPDF);
router.post('/ppt-to-pdf', upload.single('file'), validateFileSignatures, ctrl.pptToPDF);
router.post('/excel-to-pdf', upload.single('file'), validateFileSignatures, ctrl.excelToPDF);
router.post('/pdf-to-excel', upload.single('file'), validateFileSignatures, ctrl.pdfToExcel);
router.post('/pdf-to-jpg', upload.single('file'), validateFileSignatures, ctrl.pdfToJPG);
router.post('/pdf-to-png', upload.single('file'), validateFileSignatures, ctrl.pdfToPNG);
router.post('/pdf-to-text', upload.single('file'), validateFileSignatures, ctrl.pdfToText);
router.post('/pdf-to-word', upload.single('file'), validateFileSignatures, ctrl.pdfToWord);
router.post('/pdf-to-html', upload.single('file'), validateFileSignatures, ctrl.pdfToHTML);
router.post('/jpg-to-png', upload.single('file'), validateFileSignatures, ctrl.jpgToPNG);
router.post('/png-to-jpg', upload.single('file'), validateFileSignatures, ctrl.pngToJPG);
router.post('/image-to-webp', upload.single('file'), validateFileSignatures, ctrl.imageToWebP);
router.post('/jpg-to-webp', upload.single('file'), validateFileSignatures, ctrl.imageToWebP);
router.post('/png-to-webp', upload.single('file'), validateFileSignatures, ctrl.imageToWebP);
router.post('/webp-to-jpg', upload.single('file'), validateFileSignatures, ctrl.webpToJPG);
router.post('/image-to-text', upload.single('file'), validateFileSignatures, ctrl.imageToText);
router.post('/markdown-to-pdf', upload.single('file'), validateFileSignatures, ctrl.markdownToPDF);
router.post('/pdf-to-csv', upload.single('file'), validateFileSignatures, ctrl.pdfToCSV);

module.exports = router;
